### ISSUE TITLE
运行cn.enilu.flash.code.Generator报下面的错

### ISSUE THREAD

**Issue by forezp** [enilu/web-flash#20]
2019-8-10 1:4:2.79 DEBUG [main] Using 95 castor for Castors
Exception in thread "main" java.lang.RuntimeException: folder or file like '^(.+[.])(js|json)$' no found in code/code.json
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.nutz.lang.born.ConstructorBorning.born(ConstructorBorning.java:17)
	at org.nutz.lang.born.BornContext.doBorn(BornContext.java:60)
	at org.nutz.lang.Mirror.born(Mirror.java:990)
	at org.nutz.lang.Lang.makeThrow(Lang.java:149)
	at org.nutz.resource.Scans.loadResource(Scans.java:116)
	at org.nutz.ioc.loader.json.JsonLoader.<init>(JsonLoader.java:45)
	at cn.enilu.flash.code.Generator.main(Generator.java:162)

**Comment by enilu** [comment]
先把项目编译通过，再用代码生成器

**Comment by forezp** [comment]
> 先把项目编译通过，再用代码生成器

代码跑起来了啊，找不到那个config文件

**Comment by enilu** [comment]
flash-core/src/main/resources/code/code.json

**Comment by forezp** [comment]
> flash-core/src/main/resources/code/code.json

这个不太通用啊，在其他项目中不能用你这个idea插件啊，是否可以优化下啊?

**Comment by enilu** [comment]
暂时没有精力搞通用
