### ISSUE TITLE
安装完插件报错

### ISSUE THREAD

**Issue by hotsmile** [enilu/web-flash#48]
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by enilu** [comment]
可能是版本问题，我没有在太新版本的intellij IDEA商测过

**Comment by hotsmile** [comment]
我的idea是比较新的版本 2019.2.3

**Comment by aisidd** [comment]
我使用的IDEA 2020.1 也会提示错误，但是你可以忽略
只要api模块能运行起来就行。
IDEA，maven的版本都会引起报错。。运行和打包不报错就可以忽略那个错误啦

**Comment by kpub** [comment]
插件还更新吗？新版本idea菜单项都不出来。版本如下：
==================================
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to https://zhile.io
You have a perpetual fallback license for this version
Subscription is active until July 8, 2089
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: cn.enilu.webflash.generator, Lombook Plugin

**Comment by enilu** [comment]
暂时没有精力更新插件，如果代码生成插件用不了，可以自行运行Generator类来生成代码，具体传什么参数看Generator类的逻辑，插件的本质页只是调用Generator类来生成代码的
